
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    name: test
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huchx.sm.entity
