spring.profiles.active: dev


mybatis:
  type-aliases-package: com.huchx.shm.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/shj?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456